project:
  type: website
  output-dir: docs

metadata:
  year: 2025   # or whatever the current year is

execute: 
  freeze: auto

website:
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Alert** - This site is currently in a private development state and has not been published publicly."
    type: primary
    position: below-navbar
  favicon: assets/images/lab.svg
  title: "AI Exposure"
  repo-url: https://github.com/joseph-data/daioe
  repo-actions: [edit, issue]
  open-graph: true
  navbar:
    search: true
    logo: assets/images/lab.svg
    logo-alt: "AI-Econ Lab logo"
    pinned: true
    left:
      - href: index.qmd
        text: "Home"
        icon: house
      - href: about.qmd
        text: "Dashboard"
        icon: bar-chart-line
      - href: notebooks/shiny.qmd
        text: Levels
      - href: notebooks/faq.qmd
        text: FAQs
        icon: question-circle
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    background: dark    
    border: true
    left: |
      Powered by [{{< iconify simple-icons:quarto title="Quarto Logo" label="Quarto Logo" >}} Quarto](https://quarto.org).
    center: |
      Â© {{< meta year >}} AI-Econ Lab<br><br>
    right: |
      License: [CC BY NC SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0).

format:
  html:
    theme:
      light:
        - flatly
      dark:
        - slate
    toc: true
    lang: en-GB
    date-format: 'dddd[, the] Do [of] MMMM, YYYY'
    highlight-style: github
    code-copy: true
    code-link: true
    code-overflow: wrap
    anchor-sections: true
    email-obfuscation: javascript
    link-external-newwindow: true
    link-external-icon: false
    smooth-scroll: true
    respect-user-color-scheme: true


lightbox: auto
