project:
  type: website
  output-dir: docs

metadata:
  year: 2025   # or whatever the current year is

execute: 
  freeze: auto

website:
  favicon: assets/images/lab.svg
  title: "DAIOE"
  repo-url: https://github.com/joseph-data/daioe
  repo-actions: [edit, issue]
  open-graph: true
  navbar:
    search: true
    logo: assets/images/lab.svg
    logo-alt: "AI-Econ Lab logo"
    pinned: true
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: Explorer
      - href: notebooks/shiny.qmd
        text: shinylive
      - href: notebooks/faq.qmd
        text: FAQs
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    background: dark    
    border: false
    left: |
      Powered by [{{< iconify simple-icons:quarto title="Quarto Logo" label="Quarto Logo" >}} Quarto](https://quarto.org).
    center: |
      Â© {{< meta year >}} AI-Econ Lab<br><br>
    right: |
      License: [CC BY NC SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0).

format:
  html:
    theme:
      light:
        - spacelab
        - brand
        - assets/stylesheets/theme.scss
        - assets/stylesheets/projects.scss
      dark:
        - spacelab
        - brand
        - assets/stylesheets/theme.scss
        - assets/stylesheets/projects.scss
    # css: styles.css
    toc: true
    lang: en-GB
    date-format: 'dddd[, the] Do [of] MMMM, YYYY'
    highlight-style: github
    code-copy: true
    code-link: true
    code-overflow: wrap
    anchor-sections: true
    email-obfuscation: javascript
    link-external-newwindow: true

lightbox: auto
