project:
  type: website
  output-dir: docs

metadata:
  year: 2025   # or whatever the current year is

execute: 
  freeze: auto

website:
  reader-mode: true
  google-analytics: "G-W37DRJ0QYC"
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Alert** - This site is currently in a private development state and has not been published!"
    type: primary
    position: below-navbar
  favicon: assets/images/lab.svg
  title: "DAIOE"
  repo-url: https://github.com/joseph-data/daioe
  repo-actions: [edit, issue]
  open-graph: true
  navbar:
    search: true
    logo: assets/images/lab.svg
    logo-alt: "AI-Econ Lab logo"
    pinned: true
    left:
      - href: index.qmd
        text: "Home"
        icon: house
      - href: about.qmd
        text: "Explore"
        icon: bar-chart-line
      - text: "Help"
        menu:
          - text: "Ask a Question"
            icon: "chat-right-text"
            href: "https://github.com/joseph-data/daioe_dataset/discussions"
          - text: "FAQs"
            icon: "question-circle"
            href: notebooks/faq.qmd
  sidebar:
    # logo: assets/images/lab.svg
    id: explore
    collapse-level: 3
    title: "Explore"
    style: docked
    # background: light
    contents: 
      - text: "Overview"
        href: about.qmd
      - text: "Dashboard"
        href: notebooks/01_dashboard.qmd
      - text: "Employment Changes by AI Exposure"
        href: notebooks/02_employment_change.qmd
      - text: "Occupations Employed by Age"
        href: notebooks/03_occupation_by_exposure.qmd


  page-navigation: true
  back-to-top-navigation: true
  bread-crumbs: true
  page-footer:
    # background: dark    
    border: True
    left: |
      <br>Powered by [{{< iconify simple-icons:quarto title="Quarto Logo" label="Quarto Logo" >}} Quarto](https://quarto.org)<br>
    center: |
      <br>Â© {{< meta year >}} AI-Econ Lab<br>
    right: |
      <br>License: [CC BY NC SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0)<br>

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    toc: true
    lang: en-GB
    date-format: 'dddd[, the] Do [of] MMMM, YYYY'
    highlight-style: github
    code-copy: true
    code-link: true
    code-overflow: wrap
    anchor-sections: true
    email-obfuscation: javascript
    link-external-newwindow: true
    link-external-icon: false
    smooth-scroll: true
    respect-user-color-scheme: true
    crossrefs-hover: true


lightbox: auto
